# Form implementation generated from reading ui file 'a:\IDAT\Ciclo_2\Certificador\Inventario_py\Inventario_py\ui\estado_form_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Estado_form_dialog(object):
    def setupUi(self, Estado_form_dialog):
        Estado_form_dialog.setObjectName("Estado_form_dialog")
        Estado_form_dialog.resize(450, 355)
        Estado_form_dialog.setMaximumSize(QtCore.QSize(500, 355))
        Estado_form_dialog.setStyleSheet("QDialog {\n"
"    background-color: #26282A;\n"
"}")
        self.lbl_titulo = QtWidgets.QLabel(parent=Estado_form_dialog)
        self.lbl_titulo.setGeometry(QtCore.QRect(130, 10, 201, 21))
        self.lbl_titulo.setStyleSheet("color: #fff;\n"
"font-size:16px;")
        self.lbl_titulo.setObjectName("lbl_titulo")
        self.lbl_asunto = QtWidgets.QLabel(parent=Estado_form_dialog)
        self.lbl_asunto.setGeometry(QtCore.QRect(20, 83, 51, 16))
        self.lbl_asunto.setStyleSheet("color: #fff;\n"
"font-size:14px;")
        self.lbl_asunto.setObjectName("lbl_asunto")
        self.txt_asunto = QtWidgets.QLineEdit(parent=Estado_form_dialog)
        self.txt_asunto.setGeometry(QtCore.QRect(110, 78, 311, 31))
        self.txt_asunto.setStyleSheet("QLineEdit {\n"
"    background-color: #1D1F20;\n"
"    border-radius:7px;\n"
"}")
        self.txt_asunto.setObjectName("txt_asunto")
        self.lbl_descripcion = QtWidgets.QLabel(parent=Estado_form_dialog)
        self.lbl_descripcion.setGeometry(QtCore.QRect(20, 128, 71, 16))
        self.lbl_descripcion.setStyleSheet("color: #fff;\n"
"font-size:14px;")
        self.lbl_descripcion.setObjectName("lbl_descripcion")
        self.txt_descripcion = QtWidgets.QLineEdit(parent=Estado_form_dialog)
        self.txt_descripcion.setGeometry(QtCore.QRect(110, 124, 311, 31))
        self.txt_descripcion.setStyleSheet("QLineEdit {\n"
"    background-color: #1D1F20;\n"
"    border-radius:7px;\n"
"}")
        self.txt_descripcion.setObjectName("txt_descripcion")
        self.lbl_estado = QtWidgets.QLabel(parent=Estado_form_dialog)
        self.lbl_estado.setGeometry(QtCore.QRect(20, 172, 71, 16))
        self.lbl_estado.setStyleSheet("color: #fff;\n"
"font-size:14px;")
        self.lbl_estado.setObjectName("lbl_estado")
        self.cbo_estado = QtWidgets.QComboBox(parent=Estado_form_dialog)
        self.cbo_estado.setGeometry(QtCore.QRect(110, 170, 311, 25))
        self.cbo_estado.setStyleSheet("QComboBox {\n"
"    color:#fff;\n"
"    border:none;\n"
"    font-size:11px;\n"
"    background-color:#1D1F20;\n"
"    border-radius:7px;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    width: 20px;           /* espacio visible para la flecha */\n"
"      color:#fff;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    color: white;\n"
"    background-color:#1D1F20;\n"
"    selection-color: white;\n"
"    border:none;\n"
"}")
        self.cbo_estado.setObjectName("cbo_estado")
        self.cbo_estado.addItem("")
        self.cbo_estado.addItem("")
        self.cbo_estado.addItem("")
        self.cbo_estado.addItem("")
        self.cbo_estado.addItem("")
        self.cbo_estado.addItem("")
        self.btn_agregar = QtWidgets.QPushButton(parent=Estado_form_dialog)
        self.btn_agregar.setGeometry(QtCore.QRect(340, 230, 78, 36))
        self.btn_agregar.setStyleSheet("QPushButton {\n"
"    color: #111315;\n"
"    background-color: #42BE65;\n"
"    border: none;\n"
"    border-radius: 3.5px;\n"
"    font-weight: 600;\n"
"}")
        self.btn_agregar.setIconSize(QtCore.QSize(16, 16))
        self.btn_agregar.setObjectName("btn_agregar")
        self.btn_cancelar = QtWidgets.QPushButton(parent=Estado_form_dialog)
        self.btn_cancelar.setGeometry(QtCore.QRect(240, 230, 78, 36))
        self.btn_cancelar.setStyleSheet("QPushButton {\n"
"    color: #fff;\n"
"    background-color: #1D1F20;\n"
"    border: none;\n"
"    border-radius: 3.5px;\n"
"    font-weight: 600;\n"
"}")
        self.btn_cancelar.setIconSize(QtCore.QSize(16, 16))
        self.btn_cancelar.setObjectName("btn_cancelar")

        self.retranslateUi(Estado_form_dialog)
        QtCore.QMetaObject.connectSlotsByName(Estado_form_dialog)

    def retranslateUi(self, Estado_form_dialog):
        _translate = QtCore.QCoreApplication.translate
        Estado_form_dialog.setWindowTitle(_translate("Estado_form_dialog", "Formulario"))
        self.lbl_titulo.setText(_translate("Estado_form_dialog", "Agregar Estado de Inventario"))
        self.lbl_asunto.setText(_translate("Estado_form_dialog", "Asunto: "))
        self.lbl_descripcion.setText(_translate("Estado_form_dialog", "Descripción"))
        self.lbl_estado.setText(_translate("Estado_form_dialog", "Estado"))
        self.cbo_estado.setItemText(0, _translate("Estado_form_dialog", "Selecciona un estado"))
        self.cbo_estado.setItemText(1, _translate("Estado_form_dialog", "---"))
        self.cbo_estado.setItemText(2, _translate("Estado_form_dialog", "Urgente"))
        self.cbo_estado.setItemText(3, _translate("Estado_form_dialog", "Baja prioridad"))
        self.cbo_estado.setItemText(4, _translate("Estado_form_dialog", "Completado"))
        self.cbo_estado.setItemText(5, _translate("Estado_form_dialog", "En progreso"))
        self.btn_agregar.setText(_translate("Estado_form_dialog", "Agregar"))
        self.btn_cancelar.setText(_translate("Estado_form_dialog", "Cancelar"))
