# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from utils.utils import resource_path

class Ui_LoginDialog(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1139, 700)
        MainWindow.setMaximumSize(QtCore.QSize(1139, 700))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1139, 700))
        self.label.setStyleSheet("")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(resource_path("resources/img/login_model.png")))
        self.label.setObjectName("label")
        self.txt_user = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txt_user.setGeometry(QtCore.QRect(488, 315, 582, 62))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(-1)
        font.setBold(True)
        self.txt_user.setFont(font)
        self.txt_user.setStyleSheet("QLineEdit {\n"
"    border-radius: 18px;\n"
"    background-color:#26282A;\n"
"    padding:18px;\n"
"    font-size:17px;\n"
"    color:#fff;\n"
"    font-family:Open Sans;\n"
"    font-weight:600;\n"
"}")
        self.txt_user.setObjectName("txt_user")
        self.txt_psw = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txt_psw.setGeometry(QtCore.QRect(488, 443, 582, 62))
        self.txt_psw.setStyleSheet("QLineEdit {\n"
"    border-radius: 18px;\n"
"    background-color:#26282A;\n"
"    padding:18px;\n"
"    font-size:17px;\n"
"    color:#fff;\n"
"    font-family:Open Sans;\n"
"    font-weight:600;\n"
"}")
        self.txt_psw.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        self.txt_psw.setObjectName("txt_psw")
        self.btn_login = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_login.setGeometry(QtCore.QRect(488, 548, 582, 62))
        self.btn_login.setStyleSheet("QPushButton {\n"
"    border-radius: 18px;\n"
"    background-color:#A2BA22;\n"
"    font-size:22px;\n"
"    color:#111315;\n"
"    font-family:Open Sans;\n"
"    font-weight:600;\n"
"}")
        self.btn_login.setObjectName("btn_login")
        self.w_user2 = QtWidgets.QWidget(parent=self.centralwidget)
        self.w_user2.setGeometry(QtCore.QRect(245, 351, 145, 164))
        self.w_user2.setStyleSheet("QWidget {\n"
"    border-radius: 18px;\n"
"    background-color:#A2BA22;\n"
"}")
        self.w_user2.setObjectName("w_user2")
        self.lbl_name_2 = QtWidgets.QLabel(parent=self.w_user2)
        self.lbl_name_2.setGeometry(QtCore.QRect(0, 107, 145, 20))
        self.lbl_name_2.setStyleSheet("QLabel {\n"
"    font-family: Open Sans;\n"
"    font-weight: 600;\n"
"    font-size:15px;\n"
"   /* alignment for qt */\n"
"    qproperty-alignment: \'AlignCenter\';\n"
"}")
        self.lbl_name_2.setObjectName("lbl_name_2")
        self.lbl_job_2 = QtWidgets.QLabel(parent=self.w_user2)
        self.lbl_job_2.setGeometry(QtCore.QRect(0, 129, 145, 20))
        self.lbl_job_2.setStyleSheet("QLabel {\n"
"    font-family: Open Sans;\n"
"    font-weight: 600;\n"
"    font-size:13px;\n"
"   /* alignment for qt */\n"
"    qproperty-alignment: \'AlignCenter\';\n"
"}")
        self.lbl_job_2.setObjectName("lbl_job_2")
        self.lbl_pic_2 = QtWidgets.QLabel(parent=self.w_user2)
        self.lbl_pic_2.setGeometry(QtCore.QRect(34, 17, 76, 76))
        self.lbl_pic_2.setStyleSheet("")
        self.lbl_pic_2.setText("")
        self.lbl_pic_2.setPixmap(QtGui.QPixmap(resource_path("resources/img/pic_login_2.png")))
        self.lbl_pic_2.setObjectName("lbl_pic_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.txt_user.setPlaceholderText(_translate("MainWindow", "Ingresa tu usuario"))
        self.txt_psw.setPlaceholderText(_translate("MainWindow", "Ingresa tu contraseña"))
        self.btn_login.setText(_translate("MainWindow", "Ingresar"))
        self.lbl_name_2.setText(_translate("MainWindow", "Alina Schmen"))
        self.lbl_job_2.setText(_translate("MainWindow", "Secretaria"))
