# Form implementation generated from reading ui file 'a:\IDAT\Ciclo_2\Certificador\Inventario_py\Inventario_py\ui\login_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_LoginDialog(object):
    def setupUi(self, LoginDialog):
        LoginDialog.setObjectName("LoginDialog")
        LoginDialog.resize(1139, 700)
        LoginDialog.setMaximumSize(QtCore.QSize(1139, 700))
        self.label = QtWidgets.QLabel(parent=LoginDialog)
        self.label.setGeometry(QtCore.QRect(0, 0, 1139, 700))
        self.label.setMaximumSize(QtCore.QSize(1139, 700))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("a:\\IDAT\\Ciclo_2\\Certificador\\Inventario_py\\Inventario_py\\ui\\../resources/img/login_model.png"))
        self.label.setObjectName("label")
        self.txt_psw = QtWidgets.QLineEdit(parent=LoginDialog)
        self.txt_psw.setGeometry(QtCore.QRect(488, 443, 582, 62))
        self.txt_psw.setStyleSheet("QLineEdit {\n"
"    border-radius: 18px;\n"
"    background-color:#26282A;\n"
"    padding:18px;\n"
"    font-size:17px;\n"
"    color:#fff;\n"
"    font-family:Open Sans;\n"
"    font-weight:600;\n"
"}")
        self.txt_psw.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.txt_psw.setObjectName("txt_psw")
        self.txt_user = QtWidgets.QLineEdit(parent=LoginDialog)
        self.txt_user.setGeometry(QtCore.QRect(488, 315, 582, 62))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(-1)
        font.setBold(True)
        self.txt_user.setFont(font)
        self.txt_user.setStyleSheet("QLineEdit {\n"
"    border-radius: 18px;\n"
"    background-color:#26282A;\n"
"    padding:18px;\n"
"    font-size:17px;\n"
"    color:#fff;\n"
"    font-family:Open Sans;\n"
"    font-weight:600;\n"
"}")
        self.txt_user.setObjectName("txt_user")
        self.btn_login = QtWidgets.QPushButton(parent=LoginDialog)
        self.btn_login.setGeometry(QtCore.QRect(488, 548, 582, 62))
        self.btn_login.setStyleSheet("QPushButton {\n"
"    border-radius: 18px;\n"
"    background-color:#A2BA22;\n"
"    font-size:22px;\n"
"    color:#111315;\n"
"    font-family:Open Sans;\n"
"    font-weight:600;\n"
"}")
        self.btn_login.setObjectName("btn_login")
        self.w_user2 = QtWidgets.QWidget(parent=LoginDialog)
        self.w_user2.setGeometry(QtCore.QRect(245, 351, 145, 164))
        self.w_user2.setStyleSheet("QWidget {\n"
"    border-radius: 18px;\n"
"    background-color:#A2BA22;\n"
"}")
        self.w_user2.setObjectName("w_user2")
        self.lbl_name_2 = QtWidgets.QLabel(parent=self.w_user2)
        self.lbl_name_2.setGeometry(QtCore.QRect(0, 107, 145, 20))
        self.lbl_name_2.setStyleSheet("QLabel {\n"
"    font-family: Open Sans;\n"
"    font-weight: 600;\n"
"    font-size:15px;\n"
"   /* alignment for qt */\n"
"    qproperty-alignment: \'AlignCenter\';\n"
"}")
        self.lbl_name_2.setObjectName("lbl_name_2")
        self.lbl_job_2 = QtWidgets.QLabel(parent=self.w_user2)
        self.lbl_job_2.setGeometry(QtCore.QRect(0, 129, 145, 20))
        self.lbl_job_2.setStyleSheet("QLabel {\n"
"    font-family: Open Sans;\n"
"    font-weight: 600;\n"
"    font-size:13px;\n"
"   /* alignment for qt */\n"
"    qproperty-alignment: \'AlignCenter\';\n"
"}")
        self.lbl_job_2.setObjectName("lbl_job_2")
        self.lbl_pic_2 = QtWidgets.QLabel(parent=self.w_user2)
        self.lbl_pic_2.setGeometry(QtCore.QRect(34, 24, 76, 76))
        self.lbl_pic_2.setStyleSheet("")
        self.lbl_pic_2.setText("")
        self.lbl_pic_2.setPixmap(QtGui.QPixmap("a:\\IDAT\\Ciclo_2\\Certificador\\Inventario_py\\Inventario_py\\ui\\../resources/img/pic_login_2.png"))
        self.lbl_pic_2.setObjectName("lbl_pic_2")
        self.label_message = QtWidgets.QLabel(parent=LoginDialog)
        self.label_message.setGeometry(QtCore.QRect(630, 640, 301, 16))
        self.label_message.setText("")
        self.label_message.setObjectName("label_message")

        self.retranslateUi(LoginDialog)
        QtCore.QMetaObject.connectSlotsByName(LoginDialog)

    def retranslateUi(self, LoginDialog):
        _translate = QtCore.QCoreApplication.translate
        LoginDialog.setWindowTitle(_translate("LoginDialog", "Dialog"))
        self.txt_psw.setPlaceholderText(_translate("LoginDialog", "Ingresa tu contraseña"))
        self.txt_user.setPlaceholderText(_translate("LoginDialog", "Ingresa tu usuario"))
        self.btn_login.setText(_translate("LoginDialog", "Ingresar"))
        self.lbl_name_2.setText(_translate("LoginDialog", "Alina Schmen"))
        self.lbl_job_2.setText(_translate("LoginDialog", "Secretaria"))
