# Form implementation generated from reading ui file 'a:\IDAT\Ciclo_2\Certificador\Inventario_py\Inventario_py\ui\menu.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1300, 700)
        MainWindow.setMaximumSize(QtCore.QSize(1300, 700))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("QWidget {\n"
"    font-family:Open Sans;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.sidebar = QtWidgets.QWidget(parent=self.centralwidget)
        self.sidebar.setGeometry(QtCore.QRect(0, 0, 247, 700))
        self.sidebar.setStyleSheet("QWidget {\n"
"    background-color: #26282A;\n"
"}\n"
"\n"
"QPushButton {\n"
"    border:none;\n"
"    border-radius:9px;\n"
"    font-weight:700;\n"
"    font-size:16px;\n"
"    text-align:left;\n"
"    color:#fff;\n"
"    padding-left:10px;\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    background-color:#A2BA22;\n"
"    color:#26282A;\n"
"}")
        self.sidebar.setObjectName("sidebar")
        self.lbl_menu = QtWidgets.QLabel(parent=self.sidebar)
        self.lbl_menu.setGeometry(QtCore.QRect(26, 40, 49, 16))
        self.lbl_menu.setStyleSheet("QLabel {\n"
"    color:#fff;\n"
"    font-size:12px;\n"
"    font-weight:700;\n"
"}")
        self.lbl_menu.setObjectName("lbl_menu")
        self.btn_inicio = QtWidgets.QPushButton(parent=self.sidebar)
        self.btn_inicio.setGeometry(QtCore.QRect(26, 90, 196, 40))
        self.btn_inicio.setStyleSheet("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("a:\\IDAT\\Ciclo_2\\Certificador\\Inventario_py\\Inventario_py\\ui\\../ressources/img/icon_off_home.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon.addPixmap(QtGui.QPixmap("a:\\IDAT\\Ciclo_2\\Certificador\\Inventario_py\\Inventario_py\\ui\\../ressources/img/icon_on_home.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.btn_inicio.setIcon(icon)
        self.btn_inicio.setCheckable(True)
        self.btn_inicio.setChecked(True)
        self.btn_inicio.setAutoExclusive(True)
        self.btn_inicio.setObjectName("btn_inicio")
        self.btn_inventario = QtWidgets.QPushButton(parent=self.sidebar)
        self.btn_inventario.setGeometry(QtCore.QRect(26, 160, 196, 40))
        self.btn_inventario.setStyleSheet("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("a:\\IDAT\\Ciclo_2\\Certificador\\Inventario_py\\Inventario_py\\ui\\../ressources/img/icon_off_inventario.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon1.addPixmap(QtGui.QPixmap("a:\\IDAT\\Ciclo_2\\Certificador\\Inventario_py\\Inventario_py\\ui\\../ressources/img/icon_on_inventario.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.btn_inventario.setIcon(icon1)
        self.btn_inventario.setCheckable(True)
        self.btn_inventario.setAutoExclusive(True)
        self.btn_inventario.setObjectName("btn_inventario")
        self.btn_proveedores = QtWidgets.QPushButton(parent=self.sidebar)
        self.btn_proveedores.setGeometry(QtCore.QRect(26, 230, 196, 40))
        self.btn_proveedores.setStyleSheet("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("a:\\IDAT\\Ciclo_2\\Certificador\\Inventario_py\\Inventario_py\\ui\\../ressources/img/icon_off_proveedor.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon2.addPixmap(QtGui.QPixmap("a:\\IDAT\\Ciclo_2\\Certificador\\Inventario_py\\Inventario_py\\ui\\../ressources/img/icon_on_proveedor.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.btn_proveedores.setIcon(icon2)
        self.btn_proveedores.setCheckable(True)
        self.btn_proveedores.setAutoExclusive(True)
        self.btn_proveedores.setObjectName("btn_proveedores")
        self.btn_usuarios = QtWidgets.QPushButton(parent=self.sidebar)
        self.btn_usuarios.setGeometry(QtCore.QRect(26, 300, 196, 40))
        self.btn_usuarios.setStyleSheet("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("a:\\IDAT\\Ciclo_2\\Certificador\\Inventario_py\\Inventario_py\\ui\\../ressources/img/icon_off_proveedor.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_usuarios.setIcon(icon3)
        self.btn_usuarios.setCheckable(True)
        self.btn_usuarios.setAutoExclusive(True)
        self.btn_usuarios.setObjectName("btn_usuarios")
        self.btn_estados = QtWidgets.QPushButton(parent=self.sidebar)
        self.btn_estados.setGeometry(QtCore.QRect(26, 370, 196, 40))
        self.btn_estados.setStyleSheet("")
        self.btn_estados.setIcon(icon3)
        self.btn_estados.setCheckable(True)
        self.btn_estados.setAutoExclusive(True)
        self.btn_estados.setObjectName("btn_estados")
        self.mainbar = QtWidgets.QWidget(parent=self.centralwidget)
        self.mainbar.setGeometry(QtCore.QRect(247, 0, 1053, 700))
        self.mainbar.setStyleSheet("QWidget {\n"
"    background-color:#111315;\n"
"}")
        self.mainbar.setObjectName("mainbar")
        self.header = QtWidgets.QWidget(parent=self.mainbar)
        self.header.setGeometry(QtCore.QRect(530, 55, 499, 48))
        self.header.setObjectName("header")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.header)
        self.lineEdit.setGeometry(QtCore.QRect(0, 0, 411, 48))
        self.lineEdit.setStyleSheet("QLineEdit {\n"
"    background-color:#26282A;\n"
"    border:none;\n"
"    border-radius:18px;\n"
"    color:#929394;\n"
"    font-size:16px;\n"
"    padding-left:20px;\n"
"}")
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(parent=self.header)
        self.label_2.setGeometry(QtCore.QRect(440, 0, 48, 48))
        self.label_2.setStyleSheet("QLabel {\n"
"}")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("a:\\IDAT\\Ciclo_2\\Certificador\\Inventario_py\\Inventario_py\\ui\\../ressources/img/pic_profile.png"))
        self.label_2.setObjectName("label_2")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.mainbar)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 109, 1051, 591))
        self.stackedWidget.setObjectName("stackedWidget")
        self.inicio_page = QtWidgets.QWidget()
        self.inicio_page.setObjectName("inicio_page")
        self.label_4 = QtWidgets.QLabel(parent=self.inicio_page)
        self.label_4.setGeometry(QtCore.QRect(32, 0, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(-1)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("QLabel {\n"
"    color:#fff;\n"
"    font-size:28px;\n"
"}\n"
"\n"
"")
        self.label_4.setObjectName("label_4")
        self.label_8 = QtWidgets.QLabel(parent=self.inicio_page)
        self.label_8.setGeometry(QtCore.QRect(32, 45, 321, 41))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(-1)
        font.setBold(False)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("QLabel {\n"
"    color:#fff;\n"
"    font-size:14px;\n"
"    font-weight:100;\n"
"}\n"
"\n"
"")
        self.label_8.setObjectName("label_8")
        self.w_problemas = QtWidgets.QWidget(parent=self.inicio_page)
        self.w_problemas.setGeometry(QtCore.QRect(30, 100, 258, 106))
        self.w_problemas.setStyleSheet("QWidget {\n"
"    background-color:#26282A;\n"
"    border-radius:18px;\n"
"}")
        self.w_problemas.setObjectName("w_problemas")
        self.label = QtWidgets.QLabel(parent=self.w_problemas)
        self.label.setGeometry(QtCore.QRect(25, 23, 49, 31))
        self.label.setStyleSheet("QLabel {\n"
"    color:#fff;\n"
"    font-size:40px;\n"
"}")
        self.label.setObjectName("label")
        self.label_9 = QtWidgets.QLabel(parent=self.w_problemas)
        self.label_9.setGeometry(QtCore.QRect(82, 25, 31, 28))
        self.label_9.setStyleSheet("")
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("a:\\IDAT\\Ciclo_2\\Certificador\\Inventario_py\\Inventario_py\\ui\\../ressources/img/icon_warning.png"))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(parent=self.w_problemas)
        self.label_10.setGeometry(QtCore.QRect(28, 63, 211, 16))
        self.label_10.setStyleSheet("QLabel {\n"
"    color:#fff;\n"
"    font-size:13px;\n"
"    font-weight:100;\n"
"}")
        self.label_10.setObjectName("label_10")
        self.w_problemas_2 = QtWidgets.QWidget(parent=self.inicio_page)
        self.w_problemas_2.setGeometry(QtCore.QRect(310, 100, 258, 106))
        self.w_problemas_2.setStyleSheet("QWidget {\n"
"    background-color:#26282A;\n"
"    border-radius:18px;\n"
"}")
        self.w_problemas_2.setObjectName("w_problemas_2")
        self.label_14 = QtWidgets.QLabel(parent=self.w_problemas_2)
        self.label_14.setGeometry(QtCore.QRect(25, 23, 49, 31))
        self.label_14.setStyleSheet("QLabel {\n"
"    color:#fff;\n"
"    font-size:40px;\n"
"}")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(parent=self.w_problemas_2)
        self.label_15.setGeometry(QtCore.QRect(82, 25, 31, 28))
        self.label_15.setStyleSheet("")
        self.label_15.setText("")
        self.label_15.setPixmap(QtGui.QPixmap("a:\\IDAT\\Ciclo_2\\Certificador\\Inventario_py\\Inventario_py\\ui\\../ressources/img/icon_waiting.png"))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(parent=self.w_problemas_2)
        self.label_16.setGeometry(QtCore.QRect(28, 63, 211, 16))
        self.label_16.setStyleSheet("QLabel {\n"
"    color:#fff;\n"
"    font-size:13px;\n"
"    font-weight:100;\n"
"}")
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(parent=self.inicio_page)
        self.label_17.setGeometry(QtCore.QRect(32, 230, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(-1)
        font.setBold(True)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("QLabel {\n"
"    color:#fff;\n"
"    font-size:16px;\n"
"    font-weight:700;\n"
"}\n"
"\n"
"")
        self.label_17.setObjectName("label_17")
        self.comboBox = QtWidgets.QComboBox(parent=self.inicio_page)
        self.comboBox.setGeometry(QtCore.QRect(840, 240, 180, 26))
        self.comboBox.setStyleSheet("QComboBox {\n"
"    color:#fff;\n"
"    border:none;\n"
"    font-size:11px;\n"
"    background-color:#1D1F20;\n"
"    border-radius:5px;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    width: 20px;           /* espacio visible para la flecha */\n"
"      color:#fff;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    color: white;\n"
"    background-color:#1D1F20;\n"
"    selection-color: white;\n"
"    border:none;\n"
"}\n"
"\n"
"")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.stackedWidget.addWidget(self.inicio_page)
        self.inventario_page = QtWidgets.QWidget()
        self.inventario_page.setObjectName("inventario_page")
        self.label_5 = QtWidgets.QLabel(parent=self.inventario_page)
        self.label_5.setGeometry(QtCore.QRect(490, 230, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color:#fff;")
        self.label_5.setObjectName("label_5")
        self.stackedWidget.addWidget(self.inventario_page)
        self.proveedores_page = QtWidgets.QWidget()
        self.proveedores_page.setObjectName("proveedores_page")
        self.label_6 = QtWidgets.QLabel(parent=self.proveedores_page)
        self.label_6.setGeometry(QtCore.QRect(600, 240, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color:#fff;")
        self.label_6.setObjectName("label_6")
        self.stackedWidget.addWidget(self.proveedores_page)
        self.usuarios_page = QtWidgets.QWidget()
        self.usuarios_page.setObjectName("usuarios_page")
        self.label_7 = QtWidgets.QLabel(parent=self.usuarios_page)
        self.label_7.setGeometry(QtCore.QRect(670, 220, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color:#fff;")
        self.label_7.setObjectName("label_7")
        self.stackedWidget.addWidget(self.usuarios_page)
        self.estados_page = QtWidgets.QWidget()
        self.estados_page.setObjectName("estados_page")
        self.label_3 = QtWidgets.QLabel(parent=self.estados_page)
        self.label_3.setGeometry(QtCore.QRect(370, 200, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:#fff;")
        self.label_3.setObjectName("label_3")
        self.stackedWidget.addWidget(self.estados_page)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lbl_menu.setText(_translate("MainWindow", "MENÚ"))
        self.btn_inicio.setText(_translate("MainWindow", "  Inicio"))
        self.btn_inventario.setText(_translate("MainWindow", "  Inventario"))
        self.btn_proveedores.setText(_translate("MainWindow", "  Proveedores"))
        self.btn_usuarios.setText(_translate("MainWindow", "  Usuarios"))
        self.btn_estados.setText(_translate("MainWindow", "  Estados"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Buscar ..."))
        self.label_4.setText(_translate("MainWindow", "Panel"))
        self.label_8.setText(_translate("MainWindow", "Revisa el rendimiento y estado de tu inventario"))
        self.label.setText(_translate("MainWindow", "10"))
        self.label_10.setText(_translate("MainWindow", "Problemas requieren atención"))
        self.label_14.setText(_translate("MainWindow", "18"))
        self.label_16.setText(_translate("MainWindow", "Materiales por expirar"))
        self.label_17.setText(_translate("MainWindow", "Estado de Inventario"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Selecciona estado"))
        self.comboBox.setItemText(1, _translate("MainWindow", "---"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Urgente"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Baja prioridad"))
        self.comboBox.setItemText(4, _translate("MainWindow", "Completado"))
        self.comboBox.setItemText(5, _translate("MainWindow", "En progreso"))
        self.label_5.setText(_translate("MainWindow", "Inventario"))
        self.label_6.setText(_translate("MainWindow", "Proveedores"))
        self.label_7.setText(_translate("MainWindow", "Usuarios"))
        self.label_3.setText(_translate("MainWindow", "Estados"))
